/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author juanyanza11
 */
public class IngresarProd extends javax.swing.JFrame {

    /**
     * @return the sw
     */
    public static javax.swing.JTextField getSw() {
        return sw;
    }

    /**
     * @param aSw the sw to set
     */
    public static void setSw(javax.swing.JTextField sw) {
        sw = sw;
    }

    public void limpiar() {
        producto.setText("");
        sCant.setText("");
        valor.setText("");
    }

    /**
     * @return the op
     */
    public String getOp() {
        return op;
    }

    /**
     * Creates new form IngresarProd
     */
    static ArrayList<Comestible> listaC = new ArrayList<Comestible>();
    static ArrayList<Utencilio> listaU = new ArrayList<Utencilio>();
    static ArrayList<Oficina> listaO = new ArrayList<Oficina>();
    static ArrayList<Industrial> listaI = new ArrayList<Industrial>();

    public IngresarProd() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        prod = new javax.swing.JLabel();
        prod1 = new javax.swing.JLabel();
        sCant = new javax.swing.JTextField();
        cant = new javax.swing.JLabel();
        producto = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        tabla = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        salir = new javax.swing.JButton();
        valoru = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        interfaz2 = new javax.swing.JButton();
        sw = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prod.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        prod.setForeground(new java.awt.Color(255, 255, 255));
        prod.setText("Cantidad:");
        getContentPane().add(prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        prod1.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        prod1.setForeground(new java.awt.Color(255, 173, 51));
        prod1.setText("I N G R E S E  U N  P R O D U C T O S T O C K");
        getContentPane().add(prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        sCant.setBackground(new java.awt.Color(2, 12, 104));
        sCant.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sCant.setForeground(new java.awt.Color(255, 255, 255));
        sCant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sCant.setCaretColor(new java.awt.Color(255, 255, 255));
        sCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCantActionPerformed(evt);
            }
        });
        sCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sCantKeyTyped(evt);
            }
        });
        getContentPane().add(sCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 230, 30));

        cant.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        cant.setForeground(new java.awt.Color(255, 255, 255));
        cant.setText("Nuevo Producto:");
        getContentPane().add(cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        producto.setBackground(new java.awt.Color(2, 12, 104));
        producto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        producto.setForeground(new java.awt.Color(255, 255, 255));
        producto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        producto.setCaretColor(new java.awt.Color(255, 255, 255));
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });
        producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productoKeyTyped(evt);
            }
        });
        getContentPane().add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 230, 30));

        agregar.setBackground(new java.awt.Color(22, 12, 104));
        agregar.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x26-add.png"))); // NOI18N
        agregar.setBorder(null);
        agregar.setBorderPainted(false);
        agregar.setContentAreaFilled(false);
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.setFocusable(false);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 90, -1));

        tabla.setBackground(new java.awt.Color(2, 12, 104));
        tabla.setBorder(null);
        tabla.setForeground(new java.awt.Color(0, 0, 0));

        tablaProd.setBackground(new java.awt.Color(2, 12, 104));
        tablaProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tablaProd.setForeground(new java.awt.Color(255, 255, 255));
        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "VALOR"
            }
        ));
        tablaProd.setFocusable(false);
        tablaProd.setGridColor(new java.awt.Color(0, 0, 0));
        tablaProd.setRowHeight(30);
        tablaProd.setShowHorizontalLines(false);
        tabla.setViewportView(tablaProd);

        getContentPane().add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 150));

        salir.setBackground(new java.awt.Color(22, 12, 104));
        salir.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x26-salir.png"))); // NOI18N
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, -1));

        valoru.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        valoru.setForeground(new java.awt.Color(255, 255, 255));
        valoru.setText("Valor/u");
        getContentPane().add(valoru, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        valor.setBackground(new java.awt.Color(2, 12, 104));
        valor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valor.setForeground(new java.awt.Color(255, 255, 255));
        valor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        valor.setCaretColor(new java.awt.Color(255, 255, 255));
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorKeyTyped(evt);
            }
        });
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 230, 30));

        interfaz2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x26-atras.png"))); // NOI18N
        interfaz2.setBorder(null);
        interfaz2.setBorderPainted(false);
        interfaz2.setContentAreaFilled(false);
        interfaz2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        interfaz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interfaz2ActionPerformed(evt);
            }
        });
        getContentPane().add(interfaz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        sw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swActionPerformed(evt);
            }
        });
        getContentPane().add(sw, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sCantActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoActionPerformed

    public void mostar() {

        String matriz[][] = new String[listaC.size()][3];
        String matriz2[][] = new String[listaU.size()][3];
        String matriz3[][] = new String[listaO.size()][3];
        String matriz4[][] = new String[listaI.size()][3];
        int b = Integer.parseInt(getSw().getText());
        // Switch Case para cada caso
        switch (b) {
            case 1:
                for (int i = 0; i < listaC.size(); i++) {
                    // Agrego campos a listLabel que es un array
                    matriz[i][0] = listaC.get(i).getProdn();
                    matriz[i][1] = Integer.toString(listaC.get(i).getCanti());
                    matriz[i][2] = Double.toString(listaC.get(i).getValor());

                }
                tablaProd.setModel(new javax.swing.table.DefaultTableModel(
                        matriz,
                        new String[]{
                            "PRODUCTO", "CANTIDAD", "VALOR"
                        }
                ));
                break;
            case 2:
                for (int i = 0; i < listaU.size(); i++) {
                    // Agrego campos a listLabel que es un array
                    matriz2[i][0] = listaU.get(i).getProdn();
                    matriz2[i][1] = Integer.toString(listaU.get(i).getCanti());
                    matriz2[i][2] = Double.toString(listaU.get(i).getValor());

                }
                tablaProd.setModel(new javax.swing.table.DefaultTableModel(
                        matriz2,
                        new String[]{
                            "PRODUCTO", "CANTIDAD", "VALOR"
                        }
                ));
                break;
            case 3:
                for (int i = 0; i < listaO.size(); i++) {
                    // Agrego campos a listLabel que es un array
                    matriz3[i][0] = listaO.get(i).getProdn();
                    matriz3[i][1] = Integer.toString(listaO.get(i).getCanti());
                    matriz3[i][2] = Double.toString(listaO.get(i).getValor());

                }
                tablaProd.setModel(new javax.swing.table.DefaultTableModel(
                        matriz3,
                        new String[]{
                            "PRODUCTO", "CANTIDAD", "VALOR"
                        }
                ));
                break;
            case 4:
                for (int i = 0; i < listaI.size(); i++) {
                    // Agrego campos a listLabel que es un array
                    matriz4[i][0] = listaI.get(i).getProdn();
                    matriz4[i][1] = Integer.toString(listaI.get(i).getCanti());
                    matriz4[i][2] = Double.toString(listaI.get(i).getValor());

                }
                tablaProd.setModel(new javax.swing.table.DefaultTableModel(
                        matriz4,
                        new String[]{
                            "PRODUCTO", "CANTIDAD", "VALOR"
                        }
                ));
                break;

        }

    }
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        int a = Integer.parseInt(getSw().getText());

        switch (a) {
            case 1:
                String p1 = producto.getText();
                String c1 = sCant.getText();
                String v1 = valor.getText();
                double v = Double.parseDouble(v1);
                int c = Integer.parseInt(c1);
                Comestible obj = new Comestible(c, p1, v);
                listaC.add(obj);
                mostar();
                limpiar();
                break;

            case 2:
                String pU = producto.getText();
                String c2 = sCant.getText();
                String v2 = valor.getText();
                double vU = Double.parseDouble(v2);
                int cU = Integer.parseInt(c2);
                Utencilio obj2 = new Utencilio(cU, pU, vU);
                listaU.add(obj2);
                mostar();
                limpiar();

                break;
            case 3:
                p1 = producto.getText();
                c1 = sCant.getText();
                v1 = valor.getText();
                v = Double.parseDouble(v1);
                c = Integer.parseInt(c1);
                Oficina obj3 = new Oficina(c, p1, v);
                listaO.add(obj3);
                mostar();
                limpiar();

                break;
            case 4:
                p1 = producto.getText();
                c1 = sCant.getText();
                v1 = valor.getText();
                v = Double.parseDouble(v1);
                c = Integer.parseInt(c1);
                Industrial obj4 = new Industrial(c, p1, v);
                listaI.add(obj4);
                mostar();
                limpiar();
                break;
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }
    }//GEN-LAST:event_productoKeyTyped

    private void sCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sCantKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            agregar.doClick();
            char tecla2 = evt.getKeyChar();
            if (tecla2 == KeyEvent.VK_ESCAPE) {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_sCantKeyTyped

    private void interfaz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interfaz2ActionPerformed
        // TODO add your handling code here:
        Interfaz2 a = new Interfaz2();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_interfaz2ActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_valorKeyTyped

    private void swActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_swActionPerformed
    public void cargar(Comestible com) {
        this.producto.setText(com.getProdn());
        this.sCant.setText(Integer.toString(com.getCanti()));
    }
    /**
     * @param args the command line arguments
     */
    private boolean band = true;
    private String op;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel cant;
    private javax.swing.JButton interfaz2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prod;
    private javax.swing.JLabel prod1;
    private javax.swing.JTextField producto;
    private javax.swing.JTextField sCant;
    private javax.swing.JButton salir;
    public static javax.swing.JTextField sw;
    private javax.swing.JScrollPane tabla;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTextField valor;
    private javax.swing.JLabel valoru;
    // End of variables declaration//GEN-END:variables
}
